services:
  api:
    container_name: linkedin_scraper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/Perfil_LK
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    command: npm run start:dev

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    command: mongod --bind_ip_all

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local